# Identitas Aplikasi
spring.application.name=inventory-service

# Ubah ke Port 8084 agar tidak bentrok dengan OMS (8083)
server.port=8084

# Koneksi ke RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Nama antrean yang harus SAMA dengan yang ada di OMS
rabbitmq.queue.inventory=inventory.reserved.queue

# Aktifkan fitur retry jika terjadi error saat memproses pesan [cite: 365, 369]
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.default-requeue-rejected=false