# Berjalan di Port 8083 sesuai desain arsitektur IFS
server.port=8083

# Koneksi ke RabbitMQ Docker
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Nama Exchange dan Queue yang akan kita buat
rabbitmq.exchange=ifs.exchange
rabbitmq.queue.inventory=inventory.reserved.queue

# JANGAN LUPA TAMBAHKAN INI: Nama Queue khusus untuk Payment
rabbitmq.queue.payment=payment.initiate.queue