# Identitas Aplikasi
spring.application.name=payment-service

# Berjalan di Port 8085 agar tidak bentrok dengan OMS (8083) dan Inventory (8084)
server.port=8085

# Koneksi ke RabbitMQ (Kantor Pos)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Nama antrean khusus Payment yang akan didengarkan
rabbitmq.queue.payment=payment.initiate.queue